"""empty message

Revision ID: a2dc0404d5cb
Revises: 0b8dbd09c8db
Create Date: 2024-01-15 12:21:37.568962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dc0404d5cb'
down_revision = '0b8dbd09c8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prueba')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='prueba_pkey'),
    sa.UniqueConstraint('email', name='prueba_email_key')
    )
    # ### end Alembic commands ###
